version: '3.8'
services:
  db:
    container_name: postgres_demo
    image: postgres:11.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: Welcome
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - db-data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4_demo
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: boistec@domain.com
      PGADMIN_DEFAULT_PASSWORD: G98w53d1026
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

networks:
  default:
    name: postgres-service_deafult
    
volumes:
 db-data:
 pgadmin-data: